import '../e2e/core/auth/login.spec.ts'
import '../e2e/apps/citas/agendas/revision-agenda/revision_agendas_con_paciente.spec.js'
import '../e2e/core/mpi/mpi-registro-con-dni.spec.ts'
import '../e2e/apps/mobile/mobile-paciente.spec.ts'
import '../e2e/apps/rup/colonoscopia.spec.js'
import '../e2e/apps/solicitud/nuevaSolicitudEntrada.spec.js'
import '../e2e/apps/rup/ejecucion/agregar-conceptos.spec.ts'
import '../e2e/apps/solicitud/liberarTurnoSolicitud.spec.js'
import '../e2e/apps/rup/internacion/estadistica-v2/ingresos.spec.ts'
import '../e2e/core/mpi/mpi-registro-de-paciente-similares.spec.js'
import '../e2e/apps/rup/elementos-rup/elemtos-rup-requeridos.spec.ts'
import '../e2e/apps/epidemiologia/buscador-ficha-epidemiologica.spec.ts'
import '../e2e/apps/rup/internacion/estadistica-v2/egresos.spec.ts'
import '../e2e/apps/buscador-prestaciones-turnos/buscador-prestaciones-turnos.spec.js' //change to ts cyupdate
//min454.spec.ts
import '../e2e/apps/rup/ejecucion/agregar-huds.spec.ts'
import '../e2e/apps/solicitud/asignarSolicitud.spec.js'
import '../e2e/apps/rup/internacion/listado-internacion/romper-validar.spec.ts'
import '../e2e/monitoreo/buscador-snomed.spec.js'