version: '2'
services:
  db:  
    image: mongo:5.0
    ports:
      - 27017:27017
    ipc: host   
  nginx:  
    ipc: host 
    image: "andesnqn/nginx:${APP}"
  api:
    ipc: host  
    image: "docker-registry.andes.gob.ar:30443/andesnqn/api:${API}"
    entrypoint: ["/wait-for-it.sh", "db:27017", "--", "node", "index.js"]
    environment:
      APP_KEY: "5gCYFZPp3dfA2m5UNElVkgRLFcFnlele"
      MONGO_MAIN: "mongodb://db:27017/andes"
      MONGO_LOGS: "mongodb://db:27017/logs"
      MONGO_PUCO: "mongodb://db:27017/andes"
      EMAIL_ACTIVE: "false"
