version: '2'
services:
  andes_db:  
    image: mongo:4.0
    container_name: andes_db
    volumes:
      - vandes:/data/db
    ports:
      - "27066:27017"    
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  andes_elasticsearch:
    image: blacktop/elasticsearch:5.5 
    container_name: andes_elastic
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - transport.host=127.0.0.1
      - http.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - velastic:/usr/share/elasticsearch/data
    ports:
      - "9266:9200"   
  andes_nginx:  
    ipc: host 
    image: "andesnqn/nginx:${APP}"
    container_name: andes_nginx
    ports:
      - "80:80"  
  andes_api:
    ipc: host  
    image: "andesnqn/api:${API}"
    container_name: andes_api
    environment:
      APP_KEY: "5gCYFZPp3dfA2m5UNElVkgRLFcFnlele"
      MONGO_MAIN: "mongodb://andes_db:27017/andes"
      MONGO_SNOMED: "mongodb://andes_db:27017/es-edition"
      MONGO_PUCO: "mongodb://andes_db:27017/padrones"
      MONGO_LOGS: "mongodb://andes_db:27017/logs"
      ELASTIC_HOST: "andes_elastic:9200"
    ports:
      - "3002:3002"
volumes:
  vandes:
  velastic:
    driver: local