version: '2.1'
services:
  db:  
    image: mongo:5.0
    healthcheck:
        test: ["CMD","mongo", "--eval", "db.adminCommand('ping')"]
        interval: 10s
        timeout: 10s
        retries: 5
  nginx:  
    ipc: host 
    image: "andesnqn/nginx:${APP}"
  api:
    depends_on:
      db:
        condition: service_healthy
    ipc: host  
    image: "andesnqn/api:${API}"
    entrypoint: ["node", "index.js"]
    environment:
      APP_KEY: "5gCYFZPp3dfA2m5UNElVkgRLFcFnlele"
      MONGO_MAIN: "mongodb://db:27017/andes"
      MONGO_LOGS: "mongodb://db:27017/logs"
      MONGO_PUCO: "mongodb://db:27017/andes"
      EMAIL_ACTIVE: "false"
