version: '2'
services:
  db:  
    image: mongo:4.0
  nginx:  
    ipc: host 
    image: "andesnqn/nginx:${APP}"
  api:
    ipc: host  
    image: "andesnqn/api:${API}"
    environment:
      APP_KEY: "5gCYFZPp3dfA2m5UNElVkgRLFcFnlele"
      MONGO_MAIN: "mongodb://db:27017/andes"
      MONGO_PUCO: "mongodb://db:27017/andes"
      MONGO_LOGS: "mongodb://db:27017/logs"