version: '2'
services:
  andes_db:  
    image: mongo:4.0
    container_name: andes_db
    volumes:
      - vandes:/data/db
    ports:
      - "27066:27017"    
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]   
volumes:
  vandes:
    driver: local
